name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node-version:
          - 14
          - 16
        architecture:
          - x64
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install Dependencies
        run: |
          npm install @sudoo/build-cli -g
          sudoo-build install
      - name: Lint
        run: |
          sudoo-build lint
      - name: Build
        run: |
          sudoo-build build
      - name: Test
        run: |
          sudoo-build coverage
      - name: Codecov
        uses: codecov/codecov-action@v1
